Repository sergiodxa/remix-utils, pull requests merged in 2021-12, with the labels that each got.

#19 Typo and grammar fixes in README.md
  README.md
Labels: documentation

#20 Upgrade Remix
  package-lock.json
  package.json
  test/server/csrf.test.ts
Labels: enhancement

#21 Deprecate Outlet and use Remix context internally
  src/react/outlet.tsx
Labels: minor change

#22 Deprecate json response helper
  .github/release.yml
  src/server/responses.ts
Labels: deprecated

#23 Fix bug in useShouldHydate
  src/react/use-should-hydrate.ts
Labels: bug

#24 Add note about deprecated features
  README.md
Labels: documentation

#25 Fix typo: useRouteData -> useLoaderData
  src/react/csrf.tsx
Labels: documentation

#27 Add useRouteData hook
  README.md
  src/react.ts
  src/react/use-route-data.tsx
Labels: enhancement

#29 README grammar update
  README.md
Labels: documentation

#30 Create DynamicLinks and DynamicLinksFunction
  README.md
  src/react.ts
  src/react/dynamic-links.tsx
  src/react/external-scripts.tsx
Labels: enhancement
