Repository sergiodxa/remix-utils, pull requests merged in 2022-11, with the labels that each got.

#105 Update how DynamicLinks, ExternalScripts and StructuredData works
  README.md
  src/react.ts
  src/react/dynamic-links.tsx
  src/react/external-scripts.tsx
  src/react/handle-conventions.ts
  src/react/matches-type.ts
  src/react/structured-data.tsx
  test/react/structured-data.test.tsx
Labels: enhancement

#107 Add createTypedSessionStorage
  README.md
  src/server.ts
  src/server/typed-cookie.ts
  src/server/typed-session.ts
  test/server/typed-cookie.test.ts
  test/server/typed-session.test.ts
Labels: enhancement

#108 Remove Promise return type from typedSession.get
  src/server/typed-session.ts
Labels: bug

#110 Add flash key support to typed sessions & cookies
  src/server/typed-cookie.ts
  src/server/typed-session.ts
  test/react.test.tsx
  test/server/get-client-locales.test.ts
  test/server/responses.test.ts
  test/server/typed-cookie.test.ts
  test/server/typed-session.test.ts
Labels: enhancement

#109 Type createAuthenticityToken
  src/server/csrf.ts
Labels: enhancement

#111 Ensure createAuthenticityToken returns a string
  src/server/csrf.ts
Labels: enhancement

#116 Add Server-Sent Events utils
  README.md
  package-lock.json
  package.json
  src/react.ts
  src/react/use-event-source.tsx
  src/server.ts
  src/server/event-stream.ts
Labels: enhancement

#117 Change useEventSource Effects dependencies
  src/react/use-event-source.tsx
Labels: enhancement

#120 Fix "bothe" typo
  README.md
Labels: documentation
