Repository sergiodxa/remix-utils, pull requests merged in 2022-12, with the labels that each got.

#121 Add rolling cookies support
  README.md
  src/react/use-event-source.tsx
  src/server.ts
  src/server/rolling-cookie.ts
  src/server/typed-cookie.ts
  test/server/rolling-cookie.test.ts
Labels: enhancement

#119 Remove correct event in useEventSource
  src/react/use-event-source.tsx
Labels: bug

#123 Fix query parameter typo
  README.md
Labels: documentation

#125 Upgrade minimum required Remix version
  README.md
  package-lock.json
  package.json
  src/react/handle-conventions.ts
  test/server/cors.test.ts
  test/server/csrf.test.ts
  test/server/get-client-locales.test.ts
  test/server/named-action.test.ts
  test/server/responses.test.ts
  test/server/rolling-cookie.test.ts
  test/server/typed-cookie.test.ts
  test/server/typed-session.test.ts
Labels: enhancement

#126 rollingCookies override destroySession
  src/server/rolling-cookie.ts
Labels: bug

#129 Add useGlobalTransitionStates, useGlobalLoadingState and useGlobalSubmittingState hooks
  README.md
  src/react/use-global-pending-state.tsx
Labels: enhancement

#130 Add DigitalOcean IP header and fix case where IPs didn't have a space after comma
  src/server/get-client-ip-address.ts
Labels: enhancement

#137 Fi lint errors
  src/server/get-client-ip-address.ts
Labels: bug
