Repository sergiodxa/remix-utils, pull requests merged in 2023-01, with the labels that each got.

#142 Add utils to preload route assets with Link header
  README.md
  src/server.ts
  src/server/preload-route-assets.ts
  test/server/preload-route-assets.test.ts
Labels: enhancement

#143 Add missing `export` for `preloadModuleAssets`
  src/server/preload-route-assets.ts
Labels: bug

#147 Deprecate `useDataRefresh`
  src/react/use-data-refresh.tsx
Labels: deprecated

#148 Deprecate `useRouteData`
  src/react/use-route-data.tsx
Labels: deprecated

#150 Add XML response helper
  README.md
  src/server/responses.ts
  test/server/responses.test.ts
Labels: enhancement

#152 Add TXT response helper
  README.md
  src/server/responses.ts
  test/server/responses.test.ts
Labels: enhancement

#149 Release v6
  README.md
  package-lock.json
  package.json
  src/common/promise.ts
  src/react.ts
  src/react/use-data-refresh.tsx
  src/react/use-locales.ts
  src/react/use-route-data.tsx
  src/server.ts
  src/server/cors.ts
  src/server/csrf.ts
  src/server/get-client-locales.ts
  src/server/is-prefetch.ts
  src/server/json-hash.ts
  src/server/named-action.ts
  src/server/preload-route-assets.ts
  src/server/responses.ts
  src/server/safe-redirect.ts
  test/server/get-client-locales.test.ts
  test/server/json-hash.test.ts
  test/server/named-action.test.ts
  test/server/preload-route-assets.test.ts
  test/server/safe-redirect.test.ts
  test/server/typed-session.test.ts
Labels: enhancement

#153 Fix renaming of `handleRequest` functions
  README.md
Labels: documentation

#156 Typo Fix: z.optiona() → z.optional()
  README.md
Labels: documentation
