Repository sergiodxa/remix-utils, pull requests merged in 2023-11, with the labels that each got.

#275 Fix broken honeypot-inputs import in README
  README.md
Labels: documentation

#276 Improve Honeypot instructions in README
  README.md
  src/server/honeypot.ts
Labels: documentation

#279 Add ExistingSearchParams util
  README.md
  package.json
  src/react/existing-search-params.tsx
Labels: enhancement

#282 Allow passing input props to ExistingSearchParams
  src/react/existing-search-params.tsx
Labels: enhancement

#283 Fix useDebounceSubmit recursively calling itself
  src/react/use-debounce-fetcher.ts
Labels: bug

#281 Deduplicate connections to SSE with useEventSource regardless of the event
  src/react/use-event-source.ts
Labels: enhancement

#284 Fix typo in docs
  README.md
Labels: documentation
