Repository sergiodxa/remix-utils, pull requests merged in 2023-04, with the labels that each got.

#169 Add component to treat anchors as client side navigation
  README.md
  src/react.ts
  src/react/anchors-as-client-side-navigation.tsx
  test/react/anchors-as-client-side-navigation.test.tsx
Labels: enhancement

#183 Add useDelegatedAnchors and PrefetchPageAnchors
  README.md
  src/react.ts
  src/react/anchors-as-client-side-navigation.tsx
  src/react/use-delegated-anchors.tsx
  test/react/use-delegated-anchors.test.tsx
Labels: enhancement

#185 Fix document code block syntax highlighting
  README.md
Labels: documentation

#184 Mention in SSE docs that support is limited by deployment platform
  README.md
Labels: documentation

#186 Fix promiseHash example
  README.md
Labels: documentation

#189 Deprecate DynamicLinks and StructuredData
  README.md
  src/react/dynamic-links.tsx
  src/react/structured-data.tsx
Labels: deprecated
