Repository sergiodxa/remix-utils, pull requests merged in 2023-10, with the labels that each got.

#242 Mention using moduleResolution: Bundler
  README.md
Labels: documentation

#245 Fix getClientLocales and useLocales docs
  README.md
Labels: documentation

#248 Import paths docs fix
  README.md
  package.json
Labels: bug

#258 Fix useGlobalNavigationState export in package.json
  package.json
Labels: bug

#257 Add Sec-Fetch utils
  README.md
  package.json
  src/server/sec-fetch.ts
Labels: enhancement

#256 Add "id" attribute to Honeypot input
  src/react/honeypot.tsx
Labels: bug

#259 Add timers utils
  README.md
  package.json
  src/common/timers.ts
  test/common/timers.test.ts
Labels: enhancement
