Repository sergiodxa/remix-utils, pull requests merged in 2025-03, with the labels that each got.

#460 Fix CSRF example in README.md
  README.md
Labels: documentation

#463 Fix unstable_createSessionMiddleware example in README
  README.md
Labels: documentation

#464 Add logger middleware
  README.md
  package.json
  src/server/middlewares/logger.test.ts
  src/server/middlewares/logger.ts
Labels: enhancement

#465 Use middleware instead of middlewares for paths
  README.md
  package.json
  src/server/middleware/logger.test.ts
  src/server/middleware/logger.ts
  src/server/middleware/session.test.ts
  src/server/middleware/session.ts
Labels: enhancement

#466 Namespace session middleware types and interfaces
  src/server/middleware/session.ts
Labels: enhancement

#468 Add singleton middleware for shared instances across requests
  README.md
  package.json
  src/server/middleware/singleton.test.ts
  src/server/middleware/singleton.ts
Labels: enhancement

#472 Add Context Storage Middleware
  README.md
  src/server/middleware/context-storage.test.ts
  src/server/middleware/context-storage.ts
Labels: enhancement

#473 Add request id middleware
  README.md
  src/server/middleware/request-id.test.ts
  src/server/middleware/request-id.ts
Labels: enhancement

#475 Add Basic Auth middleware
  README.md
  package.json
  src/server/middleware/basic-auth.test.ts
  src/server/middleware/basic-auth.ts
  src/server/middleware/test-helper.ts
Labels: enhancement

#477 Expose promise from `useDebouncedSubmit` to align with `useSubmit`
  src/react/use-debounce-submit.ts
Labels: bug

#479 Add JWK Auth middleware
  README.md
  bun.lockb
  package.json
  src/server/middleware/basic-auth.ts
  src/server/middleware/jwk-auth.test.ts
  src/server/middleware/jwk-auth.ts
Labels: enhancement
